<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login' => 'Авторизоваться',
    'Sign in' => 'Войти',
    'Forgot password?' => 'Забыли пароль?',
    'Remember me' => 'Запомнить меня',
    'Name' => 'Имя',
    'Title' => 'Название',
    'Description' => 'Описание',
    'Note' => 'Примечание',
    'Code' => 'Код',
    //roles
    'Role' => 'Роль',
    'Roles' => 'Роли',
    'Create Roles' => 'Создать роль',
    'Add role' => 'Добавить роль',
    'Delete role' => 'Удалить роль',
    'Parameters' => 'Параметры',
    'Function to get all role subjects' => 'Функция получения всех субъектов роли',
    'Update Role' => 'Обновить роль',
    //users
    'Username' => 'Логин',
    'Users' => 'Пользователи',
    'This email is already taken!' => 'Этот Email уже занят!',
    'Login' => 'Логин',
    'City' => 'Город',
    'Avatar' => 'Аватар',
    'Deleted' => 'Удален',
    'User' => 'Пользователь',
    'Manager' => 'Менеджер',
    'Senior manager' => 'Старший менеджер',
    'Administrator' => 'Администратор',
    'Senior Administrator' => 'Старший администратор',
    'Password' => 'Пароль',
    'Status' => 'Статус',
    'Birthday' => 'День рождения',
    'Sex' => 'Пол',
    'Not specified' => 'Не указан',
    'Male' => 'Мужской',
    'Female' => 'Женский',
    'You cannot give a user a status higher than or equal to yours!' => 'Нельзя ставить пользователю статус выше или равный вашему!',
    // actions
    'Create User' => 'Создать пользователя',
    'Save' => 'Сохранить',
    'Update' => 'Изменить',
    
    //
    'Hello' => 'Здравствуйте',
    'Your data for access to' => 'Ваши данные для доступа к',
    'Error creating user. Error setting password.' => 'Ошибка создания пользователя. Ошибка установки пароля.',
    'Error. Failed to save user during creation' => 'Ошибка. Не удалось сохранить пользователя во время создания.',
    'We recommend changing your password' => 'Рекомендуем сменить пароль',
    
    'Registration in' => 'Регистрация в',
    'Password reset' => 'Сброс пароля',
    'Check your email for further action' => 'Проверьте свою электронную почту для дальнейших действий',
    'An error occurred while resetting your password. Contact the site administrator' => 'Произошла ошибка при сбросе пароля. Обратитесь к администратору сайта',
    
    'Change email' => 'Смена email',
    'Incorrect E-Mail Address.' => 'Неверный адрес электронной почты.',
    'The field must not be empty.' => 'Поле не должно быть пустым.',
    'A user with the specified login and email was not found.' => 'Пользователь с указанными логином и почтой не найден.',
    'Reset password' => 'Сброс пароля',
    'Reset password for' => 'Сброс пароля для',
    'To reset your password, follow the link' => 'Для сброса своего пароля перейдите по ссылке',
];
