<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login' => 'Авторизоваться',
    'Sign in' => 'Войти',
    'Forgot password?' => 'Забыли пароль?',
    'Remember me' => 'Запомнить меня',
    'Name' => 'Имя',
    'Title' => 'Название',
    'Description' => 'Описание',
    'Note' => 'Примечание',
    'Code' => 'Код',
    //roles
    'Role' => 'Роль',
    'Roles' => 'Роли',
    'Create Roles' => 'Создать роль',
    //users
    'Users' => 'Пользователи',
    'This email is already taken!' => 'Этот Email уже занят!',
    'Login' => 'Логин',
    'City' => 'Город',
    'Avatar' => 'Аватар',
    'User' => 'Пользователь',
    'Manager' => 'Менеджер',
    'Senior manager' => 'Старший менеджер',
    'Administrator' => 'Администратор',
    'Password' => 'Пароль',
    'Sex' => 'Пол',
    'Not specified' => 'Не указан',
    'Male' => 'Мужской',
    'Female' => 'Женский',
    // actions
    'Save' => 'Сохранить',
    
    //
    'Error creating user. Error setting password.' => 'Ошибка создания пользователя. Ошибка установки пароля.',
    'Error. Failed to save user during creation' => 'Ошибка. Не удалось сохранить пользователя во время создания.'
];
